# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designs\statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticsWindow(object):
    def setupUi(self, StatisticsWindow):
        StatisticsWindow.setObjectName("StatisticsWindow")
        StatisticsWindow.resize(649, 742)
        self.centralwidget = QtWidgets.QWidget(StatisticsWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.examCounterLabel = QtWidgets.QLabel(self.centralwidget)
        self.examCounterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.examCounterLabel.setObjectName("examCounterLabel")
        self.horizontalLayout.addWidget(self.examCounterLabel)
        self.sessionCounterLabel = QtWidgets.QLabel(self.centralwidget)
        self.sessionCounterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionCounterLabel.setObjectName("sessionCounterLabel")
        self.horizontalLayout.addWidget(self.sessionCounterLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.mainLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avgExamLabel = QtWidgets.QLabel(self.centralwidget)
        self.avgExamLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avgExamLabel.setObjectName("avgExamLabel")
        self.horizontalLayout_2.addWidget(self.avgExamLabel)
        self.avgSessionLabel = QtWidgets.QLabel(self.centralwidget)
        self.avgSessionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avgSessionLabel.setObjectName("avgSessionLabel")
        self.horizontalLayout_2.addWidget(self.avgSessionLabel)
        self.mainLayout.addLayout(self.horizontalLayout_2)
        self.learnedLabel = QtWidgets.QLabel(self.centralwidget)
        self.learnedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.learnedLabel.setObjectName("learnedLabel")
        self.mainLayout.addWidget(self.learnedLabel)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 1)
        self.mainLayout.setStretch(2, 1)
        StatisticsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StatisticsWindow)
        self.statusbar.setObjectName("statusbar")
        StatisticsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StatisticsWindow)
        QtCore.QMetaObject.connectSlotsByName(StatisticsWindow)

    def retranslateUi(self, StatisticsWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticsWindow.setWindowTitle(
            _translate("StatisticsWindow", "Statystyki")
        )
        self.examCounterLabel.setText(
            _translate("StatisticsWindow", "Przeprowadzone egzaminy: 0")
        )
        self.sessionCounterLabel.setText(
            _translate("StatisticsWindow", "Ukończonych sesji: 0")
        )
        self.avgExamLabel.setText(
            _translate("StatisticsWindow", "Średni wynik egzaminów: 00.00%")
        )
        self.avgSessionLabel.setText(
            _translate("StatisticsWindow", "Średni wynik sesji: 00.00%")
        )
        self.learnedLabel.setText(
            _translate("StatisticsWindow", "Opanowane fiszki: 0")
        )
